name: Dependencies

on: pull_request

jobs:
  changeset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create/Update Changesets
        uses: ./
